# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build product-service Docker image
        run: docker build -t product-service ./product-service

      - name: Build order-service Docker image
        run: docker build -t order-service ./order-service

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8080/products > /dev/null && curl -s http://localhost:5000/orders > /dev/null; then
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Integration Test - Product Service Endpoint
        run: |
          curl -f http://localhost:8080/products

      - name: Integration Test - Create Order (invalid product)
        run: |
          curl -f -X POST http://localhost:5000/orders \
            -H "Content-Type: application/json" \
            -d '{"product_id": 9999, "quantity": 1}'

      - name: Run Order Service Unit Tests
        working-directory: order-service
        run: |
          pip install --no-cache-dir -r requirements.txt
          python -m unittest discover -v

      - name: Tear down Docker Compose
        run: docker-compose down